In [389]:
import pandas as pd

first_df = pd.read_csv('matched_events_with_groupedscore.csv')
second_df = pd.read_csv('article_event_matches_merged.csv')

In [ ]:
first_df.columns

,Date,Major events,Details,NYT N1 (Titles),NYT N2,NYT N3,Label,Indicator,event_id,events_entities,...,similarity_scores_Title,article_sim_id_Title,temporal_scores,article_id,article_title,match_score,similarity_score,temporal_score,final_scores,match_Labels
0,2020-11-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7ab68b158e4a104599df68a6818f7e478e2bb1e7c02934...,[],...,NaN,NaN,[],NaN,NaN,NaN,NaN,NaN,NaN,Invalid
1,2020-11-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,62483e46a81b946a2527bec808a423a151e39976337399...,[],...,NaN,NaN,[],NaN,NaN,NaN,NaN,NaN,NaN,Invalid
2,2020-11-03,TPLF (rebel) attacked Northern Command (Govt.),NaN,Dozens Killed in Ethiopia in Schoolyard Massacre,NaN,NaN,NaN,NaN,22b49f7df1d984b298b3cefd48edcd10bdfcce69ae4b64...,"['TPLF', 'Northern Command', 'Govt']",...,"[0.5587443709373474, 0.49578630924224854, 0.44...","[4, 6, 7, 121, 147, 293, 513, 575, 589, 650, 6...","{4: 0.7385, 6: 0.457, 7: 0.457, 121: 0.495, 14...","[4, 121, 147, 513, 575, 650, 677, 678, 851, 85...","[""ethiopia pm orders riposte after 'attack' on...","[0.5587443709373474, 0.5016520023345947, 0.449...","[0.6153846153846154, 0.5714285714285714, 0.615...","[0.7385, 0.495, 0.6817, 0.6355, 0.5809, 0.7385...","[0.5606012341473877, 0.40757513981874055, 0.46...",Valid
3,2020-11-04,Abiy declared a military offensive with state ...,NaN,"Having Made Peace Abroad, Ethiopiaâ€™s Leader Go...",NaN,NaN,NaN,NaN,01e9c5a67f4b1fe82a00c388518a50c1a7988d61a2032d...,"['Abiy', 'Tigray']",...,"[0.6526452898979187, 0.6211974620819092, 0.606...","[4, 6, 7, 9, 121, 147, 293, 513, 575, 589, 650...","{4: 0.8, 6: 0.495, 7: 0.495, 9: 0.457, 121: 0....","[4, 147, 650, 677, 851, 855, 864, 920, 1019, 1...","[""ethiopia pm orders riposte after 'attack' on...","[0.6526452898979187, 0.6435942649841309, 0.678...","[0.3076923076923077, 0.3076923076923077, 0.32,...","[0.8, 0.7385, 0.8, 0.7385, 0.7385, 0.7385, 0.4...","[0.49456891479811427, 0.4648666081057521, 0.51...",Valid
4,2020-11-05,NaN,NaN,Ethiopia Escalates Fight Against Its Powerful ...,Why Is Ethiopia at War With Itself?,NaN,NaN,NaN,6d05297a3d80dce9e185cf5e6b682c8ef5c3ed6a56b87c...,[],...,NaN,NaN,[],NaN,NaN,NaN,NaN,NaN,NaN,Invalid
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
755,2022-11-26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,c4c5f410f55a64c4aa2d67c6130a08f2c6da33b09e8721...,[],...,NaN,NaN,[],NaN,NaN,NaN,NaN,NaN,NaN,Invalid
756,2022-11-27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,d7c37e51f1d250f78100377850c61c5bdf6aed3eaba864...,[],...,NaN,NaN,[],NaN,NaN,NaN,NaN,NaN,NaN,Invalid
757,2022-11-28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,406562c863142969a17377973cef5bf37f1037a3c4c7a3...,[],...,NaN,NaN,[],NaN,NaN,NaN,NaN,NaN,NaN,Invalid
758,2022-11-29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22663429b5ef1d463bb8e388e2b3373232b7b9ff9fbdbf...,[],...,NaN,NaN,[],NaN,NaN,NaN,NaN,NaN,NaN,Invalid
759,2022-11-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,dfdaabe0beed24aa100cab21fd3c08ee70cdf3c23c8902...,[],...,NaN,NaN,[],NaN,NaN,NaN,NaN,NaN,NaN,Invalid

In [400]:
first_df.columns
first_df_cropped = first_df[['Date', 'event_id', 'Major events','article_id', 'similarity_scores_Title','article_sim_id_Title','temporal_scores','article_title','match_score','similarity_score','temporal_score','final_scores','match_Labels']]
first_df_cropped

,Date,event_id,Major events,article_id,similarity_scores_Title,article_sim_id_Title,temporal_scores,article_title,match_score,similarity_score,temporal_score,final_scores,match_Labels
0,2020-11-01,7ab68b158e4a104599df68a6818f7e478e2bb1e7c02934...,NaN,NaN,NaN,NaN,[],NaN,NaN,NaN,NaN,NaN,Invalid
1,2020-11-02,62483e46a81b946a2527bec808a423a151e39976337399...,NaN,NaN,NaN,NaN,[],NaN,NaN,NaN,NaN,NaN,Invalid
2,2020-11-03,22b49f7df1d984b298b3cefd48edcd10bdfcce69ae4b64...,TPLF (rebel) attacked Northern Command (Govt.),"[4, 121, 147, 513, 575, 650, 677, 678, 851, 85...","[0.5587443709373474, 0.49578630924224854, 0.44...","[4, 6, 7, 121, 147, 293, 513, 575, 589, 650, 6...","{4: 0.7385, 6: 0.457, 7: 0.457, 121: 0.495, 14...","[""ethiopia pm orders riposte after 'attack' on...","[0.5587443709373474, 0.5016520023345947, 0.449...","[0.6153846153846154, 0.5714285714285714, 0.615...","[0.7385, 0.495, 0.6817, 0.6355, 0.5809, 0.7385...","[0.5606012341473877, 0.40757513981874055, 0.46...",Valid
3,2020-11-04,01e9c5a67f4b1fe82a00c388518a50c1a7988d61a2032d...,Abiy declared a military offensive with state ...,"[4, 147, 650, 677, 851, 855, 864, 920, 1019, 1...","[0.6526452898979187, 0.6211974620819092, 0.606...","[4, 6, 7, 9, 121, 147, 293, 513, 575, 589, 650...","{4: 0.8, 6: 0.495, 7: 0.495, 9: 0.457, 121: 0....","[""ethiopia pm orders riposte after 'attack' on...","[0.6526452898979187, 0.6435942649841309, 0.678...","[0.3076923076923077, 0.3076923076923077, 0.32,...","[0.8, 0.7385, 0.8, 0.7385, 0.7385, 0.7385, 0.4...","[0.49456891479811427, 0.4648666081057521, 0.51...",Valid
4,2020-11-05,6d05297a3d80dce9e185cf5e6b682c8ef5c3ed6a56b87c...,NaN,NaN,NaN,NaN,[],NaN,NaN,NaN,NaN,NaN,Invalid
...,...,...,...,...,...,...,...,...,...,...,...,...,...
755,2022-11-26,c4c5f410f55a64c4aa2d67c6130a08f2c6da33b09e8721...,NaN,NaN,NaN,NaN,[],NaN,NaN,NaN,NaN,NaN,Invalid
756,2022-11-27,d7c37e51f1d250f78100377850c61c5bdf6aed3eaba864...,NaN,NaN,NaN,NaN,[],NaN,NaN,NaN,NaN,NaN,Invalid
757,2022-11-28,406562c863142969a17377973cef5bf37f1037a3c4c7a3...,NaN,NaN,NaN,NaN,[],NaN,NaN,NaN,NaN,NaN,Invalid
758,2022-11-29,22663429b5ef1d463bb8e388e2b3373232b7b9ff9fbdbf...,NaN,NaN,NaN,NaN,[],NaN,NaN,NaN,NaN,NaN,Invalid
759,2022-11-30,dfdaabe0beed24aa100cab21fd3c08ee70cdf3c23c8902...,NaN,NaN,NaN,NaN,[],NaN,NaN,NaN,NaN,NaN,Invalid

In [401]:
second_df.columns
second_df_cropped = second_df[['article_id', 'event_id', 'title', 'match_Labels']]
second_df_cropped

,article_id,event_id,title,match_Labels
0,0,['4dc83fb671cf9902099e6f44157eb4ad50c7b91390f9...,can ethiopia survive? what might happen if abi...,Valid
1,1,['534b3154c9b2170b43d067f18256b357859176de9c47...,ethiopia : eritrea confirms its troops are fig...,Valid
2,2,['56222e8f00be3dd620eb8c4e9563443c75827d576cd8...,tigray crisis - ethiopia 's tigray war spills ...,Valid
3,3,['e1ff6111870749dc616769907ae0b3e7c8c0b294f2d0...,ethiopia declares state of emergency; tigrayan...,Valid
4,4,['d0331673e997f5bdcc92d6fee85308f01a4fdb19ff70...,ethiopia pm orders riposte after 'attack' on a...,Invalid
...,...,...,...,...
3317,3317,['cc48da3e947769a367154b51bdf247ffa4f90a25bebd...,ethiopia peace talks start in south africa,Valid
3318,3318,['2270763ecb38a00674d8cedb74ca936129d7b8e54a36...,"van hollen, senate democrats press pompeo on c...",Valid
3319,3319,['0978c01466be702b312c563a2db9f68acc006cc521d5...,ethiopian rebels announce retreat to tigray re...,Valid
3320,3320,['286d5c391d7d4ef9f6cc03e94862b194d9701ca60d9d...,ethiopia civilians warns of 'no mercy' in tigr...,Valid
3321,3321,NaN,tigray capital slowly emerging from shadow of war,Invalid

In [402]:
import pandas as pd
import ast

valid_events = first_df_cropped[first_df_cropped['match_Labels'] == 'Valid'].copy()
valid_events['article_id'] = valid_events['article_id'].apply(lambda x: ast.literal_eval(x) if isinstance(x, str) else x)

In [403]:
valid_events['article_id']

2      [4, 121, 147, 513, 575, 650, 677, 678, 851, 85...
3      [4, 147, 650, 677, 851, 855, 864, 920, 1019, 1...
6      [4, 6, 7, 121, 147, 293, 513, 537, 538, 575, 5...
7      [4, 6, 7, 9, 45, 51, 100, 121, 143, 144, 147, ...
27     [4, 6, 7, 8, 9, 26, 31, 45, 51, 71, 82, 87, 90...
28     [4, 6, 7, 8, 9, 26, 31, 45, 51, 71, 82, 87, 90...
239    [18, 118, 408, 494, 763, 771, 1131, 1268, 1638...
253    [2, 11, 16, 18, 76, 96, 118, 122, 174, 201, 21...
261    [2, 16, 18, 96, 174, 201, 233, 256, 292, 337, ...
362    [3, 154, 170, 211, 278, 336, 370, 407, 433, 43...
363    [433, 449, 742, 829, 1431, 1664, 2017, 2072, 2...
364    [0, 3, 131, 154, 163, 170, 177, 181, 194, 197,...
387    [532, 612, 1202, 1487, 1736, 2767, 2768, 2811,...
392    [3, 21, 78, 88, 129, 183, 204, 228, 236, 291, ...
395    [72, 79, 183, 204, 228, 291, 339, 374, 464, 46...
399    [72, 79, 173, 183, 204, 246, 248, 339, 374, 46...
412    [21, 72, 79, 160, 173, 179, 183, 203, 204, 207...
417    [79, 160, 173, 179, 203, 204, 207, 215, 246, 2...
432    [161, 164, 189, 205, 242, 338, 534, 636, 651, ...
508    [75, 83, 119, 294, 301, 313, 318, 485, 557, 68...
664    [52, 93, 127, 490, 531, 638, 689, 700, 713, 10...
669    [23, 24, 27, 34, 38, 42, 52, 81, 93, 111, 127,...
681    [36, 81, 111, 136, 159, 340, 438, 442, 613, 62...
700    [116, 124, 196, 321, 350, 359, 385, 392, 399, ...
708    [28, 58, 190, 196, 261, 321, 346, 351, 357, 38...
715    [269, 578, 816, 1243, 1288, 2225, 2448, 2470, ...
716    [28, 39, 46, 48, 50, 53, 130, 190, 264, 269, 3...
720    [28, 39, 48, 50, 269, 307, 322, 323, 349, 401,...
723    [28, 39, 40, 46, 48, 50, 53, 58, 125, 130, 152...
731    [14, 39, 40, 50, 53, 54, 57, 107, 115, 117, 12...
741    [14, 29, 39, 40, 53, 54, 57, 115, 117, 125, 13...
Name: article_id, dtype: object

In [404]:
second_df_cropped.columns

Index(['article_id', 'event_id', 'title', 'match_Labels'], dtype='object')

In [405]:
valid_events['article_id']

2      [4, 121, 147, 513, 575, 650, 677, 678, 851, 85...
3      [4, 147, 650, 677, 851, 855, 864, 920, 1019, 1...
6      [4, 6, 7, 121, 147, 293, 513, 537, 538, 575, 5...
7      [4, 6, 7, 9, 45, 51, 100, 121, 143, 144, 147, ...
27     [4, 6, 7, 8, 9, 26, 31, 45, 51, 71, 82, 87, 90...
28     [4, 6, 7, 8, 9, 26, 31, 45, 51, 71, 82, 87, 90...
239    [18, 118, 408, 494, 763, 771, 1131, 1268, 1638...
253    [2, 11, 16, 18, 76, 96, 118, 122, 174, 201, 21...
261    [2, 16, 18, 96, 174, 201, 233, 256, 292, 337, ...
362    [3, 154, 170, 211, 278, 336, 370, 407, 433, 43...
363    [433, 449, 742, 829, 1431, 1664, 2017, 2072, 2...
364    [0, 3, 131, 154, 163, 170, 177, 181, 194, 197,...
387    [532, 612, 1202, 1487, 1736, 2767, 2768, 2811,...
392    [3, 21, 78, 88, 129, 183, 204, 228, 236, 291, ...
395    [72, 79, 183, 204, 228, 291, 339, 374, 464, 46...
399    [72, 79, 173, 183, 204, 246, 248, 339, 374, 46...
412    [21, 72, 79, 160, 173, 179, 183, 203, 204, 207...
417    [79, 160, 173, 179, 203, 204, 207, 215, 246, 2...
432    [161, 164, 189, 205, 242, 338, 534, 636, 651, ...
508    [75, 83, 119, 294, 301, 313, 318, 485, 557, 68...
664    [52, 93, 127, 490, 531, 638, 689, 700, 713, 10...
669    [23, 24, 27, 34, 38, 42, 52, 81, 93, 111, 127,...
681    [36, 81, 111, 136, 159, 340, 438, 442, 613, 62...
700    [116, 124, 196, 321, 350, 359, 385, 392, 399, ...
708    [28, 58, 190, 196, 261, 321, 346, 351, 357, 38...
715    [269, 578, 816, 1243, 1288, 2225, 2448, 2470, ...
716    [28, 39, 46, 48, 50, 53, 130, 190, 264, 269, 3...
720    [28, 39, 48, 50, 269, 307, 322, 323, 349, 401,...
723    [28, 39, 40, 46, 48, 50, 53, 58, 125, 130, 152...
731    [14, 39, 40, 50, 53, 54, 57, 107, 115, 117, 12...
741    [14, 29, 39, 40, 53, 54, 57, 115, 117, 125, 13...
Name: article_id, dtype: object

In [406]:
# Step 2: Create article_id â†’ event_id mapping for valid matches
valid_articles_map = dict(
    second_df_cropped[second_df_cropped['match_Labels'] == 'Valid'][['article_id', 'event_id']].values
)

# Step 3: Function to get valid event_ids from the article list
import ast

def find_valid_event_ids(article_list_str):
        unique_lists = [int(a) for a in article_list_str if a in valid_articles_map]
        return list(set(unique_lists))

# Step 4: Apply function to valid_events article_ids
valid_events['valid_article_ids_from_matched'] = valid_events['article_id'].apply(find_valid_event_ids)

# Step 5: Add a flag if any valid event_ids were found
valid_events['has_valid_articles'] = valid_events['valid_article_ids_from_matched'].apply(lambda x: len(x) > 0)

print(valid_events)

           Date                                           event_id  \
2    2020-11-03  22b49f7df1d984b298b3cefd48edcd10bdfcce69ae4b64...
3    2020-11-04  01e9c5a67f4b1fe82a00c388518a50c1a7988d61a2032d...
6    2020-11-07  60702b883adf1ad3acddc30c58c2b57e35e53fd1e996a4...
7    2020-11-08  33c9dfd29e0cad49f44d5a7ca70d3176da71ef03188a95...
27   2020-11-28  37525424e8e27d1c00076646567c6614421d6ea25161aa...
28   2020-11-29  343c9e0b1c87b740966cefdf419be75e4a4e95e101b767...
239  2021-06-28  143f81d0d69eb0627c5cf6b26c9ba722050070c9228488...
253  2021-07-12  d73768c1902a5931b03ec7390573bb1a8b71a933bd2b87...
261  2021-07-20  cf1904a7897e05ca57f63806ff82fa0b3ee8d5f1d884e2...
362  2021-10-29  6ce32b75ab6d09d217acc75d9b064eacb22a92829b7fbe...
363  2021-10-30  2e27c60c0eb45b4abdbc5c6837f34a172b9404c7b85c67...
364  2021-10-31  3e8f7d051a23e851a30a70e618e08d87b128fa5a3b8276...
387  2021-11-23  b506f106029e2e6256b3401c626ac5dc37982d01d00324...
392  2021-11-28  b11bca00e2d06f539ab97e9ebb4178e43dbd5c39b7dee3...
395  2021-12-01  c3b923568039d92394006d0c8af3a29de0be500b5c325a...
399  2021-12-05  87c46127a5a52c1625703c855a3c01cab2ffbdc01d0683...
412  2021-12-18  b5f96f23194bc9ff4a0fa445c607902fc09ee91e017a2c...
417  2021-12-23  e769e36b94f57c664af9e1dbcaae1dae8a05f2b1b56863...
432  2022-01-07  75d45bf06baf5f6f4b39f54232a208b708d412b7e01ae0...
508  2022-03-24  d5ec319f3b133afe468e3e49cc5b73e0d4073fd47b3031...
664  2022-08-27  eff183ec0fbb6a05e4df81109d5cd1e9ee53dd00708275...
669  2022-09-01  bdff9cb9a41cb4138d6104ee082f3dabf2938dac4b20bd...
681  2022-09-13  d89e8b1bc7f9790ed8cca60d93db9bfa7c195573effe56...
700  2022-10-02  e71a1c71835b3a2970553eeee3f7db77c6cca7981c90cf...
708  2022-10-10  86c1c0dc170fe3d47665484a6f8c8b053e990395e38cd2...
715  2022-10-17  3fbdac88569822ef64368d0aaf513137f43ad0fd0dbe8e...
716  2022-10-18  fdc393e569fcbbd52fdb89aba5c2cc3776123435fa4545...
720  2022-10-22  4551c1da29d493fbdcca52abff51df3d1123d17f4a3f1a...
723  2022-10-25  27e749068998f82400fd2382a24bdff6a44e0e999c1070...
731  2022-11-02  9b93972d450344e5b0c62d95b43a60c8f69eb8103e63cf...
741  2022-11-12  50d180485eb6d2eb0bbd059fe2ee2a01175ccc5c4e410c...

                                          Major events  \
2       TPLF (rebel) attacked Northern Command (Govt.)
3    Abiy declared a military offensive with state ...
6    Ethiopian parliament set-up an interim governm...
7    ENDF (Ethiopian National Defence Forces) offen...
27   Mekelle, capital of Tigray, captured by Federa...
28   The war continued with increasing intensity un...
239      TPLF recaptured the regional capital, Mekelle
253  TPLF captured southern Tigray including Alamat...
261             Kobo in Amhara region captured by TPLF
362  TPLF captured the town of Dessie deep in Amhar...
363  TPLF captured the town Kombolcha important man...
364  TPLF-OLA (Oromo Liberation Army) joint offensi...
387                      PM Abiy went to the war front
392           ENDF took control of Chifra, Afar Region
395  ENDF took control of Shewa Robit 220 k from Ad...
399                 ENDF captured Dessie and Kombolcha
412  Legesse Tulu, head of Government Communication...
417  Ethiopian government announced  troops will no...
432  Ethiopian government pardoned TPLF high rankin...
508  Federal Government and TPLF agreed on ceasefir...
664          Resurgence of fighting TPLF captured Kobo
669  Ethiopia and Eritrea (without official acknole...
681  Sheraro was captured by Ethiopian-Eritrean forces
700  TPLF announced it has withdrawn from Northe Wo...
708  TPLF called for full mobilisation of Tigray po...
715                  Strategic town Shire fell to ENDF
716                     ENDF captured Almata and Korem
720                        ENDF captured Adwa and Axum
723  AU (African Union) announced peace talks to be...
731  Ethiopia and TPLF announced they signed a peac...
741  Signing ceremony of the declaration of the sen...

                                            article_id  \
2    [4, 121, 147, 513, 575, 650, 677, 678, 851, 85...
3    [4, 147, 650, 677, 851, 855, 864, 920, 1019, 1...
6    [4, 6, 7, 121, 147, 293, 513, 537, 538, 575, 5...
7    [4, 6, 7, 9, 45, 51, 100, 121, 143, 144, 147, ...
27   [4, 6, 7, 8, 9, 26, 31, 45, 51, 71, 82, 87, 90...
28   [4, 6, 7, 8, 9, 26, 31, 45, 51, 71, 82, 87, 90...
239  [18, 118, 408, 494, 763, 771, 1131, 1268, 1638...
253  [2, 11, 16, 18, 76, 96, 118, 122, 174, 201, 21...
261  [2, 16, 18, 96, 174, 201, 233, 256, 292, 337, ...
362  [3, 154, 170, 211, 278, 336, 370, 407, 433, 43...
363  [433, 449, 742, 829, 1431, 1664, 2017, 2072, 2...
364  [0, 3, 131, 154, 163, 170, 177, 181, 194, 197,...
387  [532, 612, 1202, 1487, 1736, 2767, 2768, 2811,...
392  [3, 21, 78, 88, 129, 183, 204, 228, 236, 291, ...
395  [72, 79, 183, 204, 228, 291, 339, 374, 464, 46...
399  [72, 79, 173, 183, 204, 246, 248, 339, 374, 46...
412  [21, 72, 79, 160, 173, 179, 183, 203, 204, 207...
417  [79, 160, 173, 179, 203, 204, 207, 215, 246, 2...
432  [161, 164, 189, 205, 242, 338, 534, 636, 651, ...
508  [75, 83, 119, 294, 301, 313, 318, 485, 557, 68...
664  [52, 93, 127, 490, 531, 638, 689, 700, 713, 10...
669  [23, 24, 27, 34, 38, 42, 52, 81, 93, 111, 127,...
681  [36, 81, 111, 136, 159, 340, 438, 442, 613, 62...
700  [116, 124, 196, 321, 350, 359, 385, 392, 399, ...
708  [28, 58, 190, 196, 261, 321, 346, 351, 357, 38...
715  [269, 578, 816, 1243, 1288, 2225, 2448, 2470, ...
716  [28, 39, 46, 48, 50, 53, 130, 190, 264, 269, 3...
720  [28, 39, 48, 50, 269, 307, 322, 323, 349, 401,...
723  [28, 39, 40, 46, 48, 50, 53, 58, 125, 130, 152...
731  [14, 39, 40, 50, 53, 54, 57, 107, 115, 117, 12...
741  [14, 29, 39, 40, 53, 54, 57, 115, 117, 125, 13...

                               similarity_scores_Title  \
2    [0.5587443709373474, 0.49578630924224854, 0.44...
3    [0.6526452898979187, 0.6211974620819092, 0.606...
6    [0.601200520992279, 0.6149016618728638, 0.6060...
7    [0.5820202231407166, 0.5905984044075012, 0.544...
27   [0.5645926594734192, 0.5977888703346252, 0.582...
28   [0.5272127389907837, 0.5798885822296143, 0.626...
239  [0.4579665958881378, 0.5686173439025879, 0.572...
253  [0.6286035180091858, 0.589913010597229, 0.6039...
261  [0.6045465469360352, 0.5755550265312195, 0.502...
362  [0.4543534517288208, 0.5667229294776917, 0.469...
363  [0.3861372768878937, 0.49916428327560425, 0.43...
364  [0.5377827882766724, 0.729200541973114, 0.6012...
387  [0.519575834274292, 0.5192767381668091, 0.4237...
392  [0.49073541164398193, 0.5655810236930847, 0.39...
395  [0.5186766982078552, 0.41920655965805054, 0.42...
399  [0.4110916554927826, 0.46428030729293823, 0.51...
412  [0.4566322863101959, 0.3964540362358093, 0.454...
417  [0.3167884051799774, 0.5684945583343506, 0.553...
432  [0.5498521327972412, 0.5280206203460693, 0.566...
508  [0.7135055661201477, 0.44882047176361084, 0.49...
664  [0.47653940320014954, 0.4392777383327484, 0.42...
669  [0.5908374190330505, 0.5285086631774902, 0.557...
681  [0.4609645903110504, 0.47638171911239624, 0.47...
700  [0.38747918605804443, 0.4340105652809143, 0.53...
708  [0.5308921337127686, 0.44939547777175903, 0.40...
715  [0.4433594346046448, 0.38563424348831177, 0.42...
716  [0.5230609774589539, 0.4988051652908325, 0.402...
720  [0.5539960861206055, 0.515402615070343, 0.3755...
723  [0.511408805847168, 0.4203908145427704, 0.7491...
731  [0.7604167461395264, 0.5098109841346741, 0.562...
741  [0.7485524415969849, 0.6427618265151978, 0.587...

                                  article_sim_id_Title  \
2    [4, 6, 7, 121, 147, 293, 513, 575, 589, 650, 6...
3    [4, 6, 7, 9, 121, 147, 293, 513, 575, 589, 650...
6    [4, 6, 7, 9, 51, 121, 144, 147, 293, 373, 513,...
7    [4, 6, 7, 9, 45, 51, 100, 121, 143, 144, 147, ...
27   [4, 6, 7, 8, 9, 26, 31, 45, 51, 71, 82, 87, 90...
28   [4, 6, 7, 8, 9, 26, 31, 45, 51, 71, 82, 87, 90...
239  [11, 16, 18, 76, 86, 118, 122, 175, 213, 283, ...
253  [2, 11, 16, 18, 76, 96, 118, 122, 174, 175, 20...
261  [2, 5, 11, 16, 18, 76, 96, 118, 122, 174, 201,...
362  [0, 3, 131, 154, 169, 170, 194, 197, 211, 214,...
363  [0, 3, 131, 154, 163, 169, 170, 181, 194, 197,...
364  [0, 3, 131, 154, 163, 170, 177, 181, 194, 197,...
387  [0, 3, 21, 78, 88, 129, 131, 154, 163, 177, 18...
392  [0, 3, 21, 72, 78, 79, 88, 129, 131, 163, 177,...
395  [0, 21, 72, 78, 79, 88, 129, 131, 163, 177, 17...
399  [21, 72, 78, 79, 88, 129, 160, 173, 179, 183, ...
412  [21, 72, 79, 160, 173, 179, 183, 203, 204, 207...
417  [72, 79, 160, 173, 179, 203, 204, 207, 215, 21...
432  [106, 161, 164, 189, 203, 205, 207, 215, 242, ...
508  [75, 83, 119, 222, 294, 301, 313, 318, 331, 48...
664  [23, 24, 27, 34, 38, 42, 52, 61, 93, 111, 127,...
669  [23, 24, 27, 34, 38, 42, 52, 61, 81, 93, 111, ...
681  [23, 24, 34, 36, 38, 42, 52, 81, 93, 111, 127,...
700  [36, 58, 81, 116, 124, 138, 190, 196, 261, 321...
708  [28, 46, 58, 116, 124, 130, 138, 190, 196, 261...
715  [28, 39, 46, 48, 49, 50, 53, 58, 116, 124, 130...
716  [28, 39, 46, 48, 49, 50, 53, 58, 116, 124, 125...
720  [28, 39, 40, 46, 48, 49, 50, 53, 58, 107, 116,...
723  [28, 39, 40, 46, 48, 49, 50, 53, 57, 58, 107, ...
731  [14, 28, 39, 40, 46, 48, 49, 50, 53, 54, 57, 5...
741  [14, 29, 39, 40, 46, 48, 49, 50, 53, 54, 56, 5...

                                       temporal_scores  \
2    {4: 0.7385, 6: 0.457, 7: 0.457, 121: 0.495, 14...
3    {4: 0.8, 6: 0.495, 7: 0.495, 9: 0.457, 121: 0....
6    {4: 0.9231, 6: 0.6293, 7: 0.6293, 9: 0.5809, 5...
7    {4: 0.8988, 6: 0.6817, 7: 0.6817, 9: 0.6293, 4...
27   {4: 0.5273, 6: 0.6188, 7: 0.6188, 8: 0.5363, 9...
28   {4: 0.5134, 6: 0.6025, 7: 0.6025, 8: 0.5809, 9...
239  {11: 0.7385, 16: 0.6817, 18: 0.8, 76: 0.8988, ...
253  {2: 0.495, 11: 0.707, 16: 0.7261, 18: 0.6884, ...
261  {2: 0.9481, 5: 0.495, 11: 0.5712, 16: 0.5866, ...
362  {0: 0.457, 3: 0.5363, 131: 0.495, 154: 0.6817,...
363  {0: 0.495, 3: 0.5809, 131: 0.5363, 154: 0.7385...
364  {0: 0.5363, 3: 0.6293, 131: 0.5809, 154: 0.8, ...
387  {0: 0.6188, 3: 0.5866, 21: 0.8, 78: 0.7659, 88...
392  {0: 0.5415, 3: 0.5134, 21: 0.8752, 72: 0.6293,...
395  {0: 0.4999, 21: 0.8079, 72: 0.8, 78: 0.6188, 7...
399  {21: 0.7261, 72: 0.8988, 78: 0.5562, 79: 0.898...
412  {21: 0.5134, 72: 0.6355, 79: 0.6355, 160: 0.80...
417  {72: 0.5562, 79: 0.5562, 160: 0.707, 173: 0.68...
432  {106: 0.457, 161: 0.8988, 164: 0.7385, 189: 0....
508  {75: 0.7385, 83: 0.8, 119: 0.5363, 222: 0.5363...
664  {23: 0.495, 24: 0.6293, 27: 0.7458, 34: 0.7385...
669  {23: 0.7385, 24: 0.9481, 27: 0.6527, 34: 0.898...
681  {23: 0.7458, 24: 0.6884, 34: 0.6527, 36: 0.923...
700  {36: 0.5562, 58: 0.457, 81: 0.4999, 116: 0.852...
708  {28: 0.8, 46: 0.457, 58: 0.9737, 116: 0.6884, ...
715  {28: 0.8297, 39: 0.7385, 46: 0.8, 48: 0.7385, ...
716  {28: 0.8079, 39: 0.8, 46: 0.9737, 48: 0.8, 49:...
720  {28: 0.7261, 39: 0.8988, 40: 0.5809, 46: 0.875...
723  {28: 0.6703, 39: 0.8297, 40: 0.7385, 46: 0.807...
731  {14: 0.7385, 28: 0.5415, 39: 0.6703, 40: 0.829...
741  {14: 0.7866, 29: 0.9481, 39: 0.5134, 40: 0.635...

                                         article_title  \
2    ["ethiopia pm orders riposte after 'attack' on...
3    ["ethiopia pm orders riposte after 'attack' on...
6    ["ethiopia pm orders riposte after 'attack' on...
7    ["ethiopia pm orders riposte after 'attack' on...
27   ["ethiopia pm orders riposte after 'attack' on...
28   ["ethiopia pm orders riposte after 'attack' on...
239  ['ethiopia declares tigray ceasefire as rebels...
253  ["tigray crisis - ethiopia 's tigray war spill...
261  ["tigray crisis - ethiopia 's tigray war spill...
362  ['ethiopia declares state of emergency; tigray...
363  ['six killed, scores injured in latest tigray ...
364  ['can ethiopia survive? what might happen if a...
387  ['ethiopia pm reaches front line to fight rebe...
392  ['ethiopia declares state of emergency; tigray...
395  ['why mwenda will cry while kabushenga is laug...
399  ['why mwenda will cry while kabushenga is laug...
412  ['austria sees vaccination uptick; europe stru...
417  ['ethiopians abroad protest "western support f...
432  ["ethiopia says the ball to stop war is in tpl...
508  ['ethiopia war: tigray rebels agree to humanit...
664  ['fighting flares up in northern ethiopia afte...
669  ['ethiopia accuses tplf of listing child soldi...
681  ["au extends horn envoy's mission amid ethiopi...
700  ['un agency says truck hit, driver hurt in eth...
708  ["programme summary of ethiopia 's obn tv news...
715  ["three killed, including an ric aid worker, i...
716  ["programme summary of ethiopia 's obn tv news...
720  ["programme summary of ethiopia 's obn tv news...
723  ["programme summary of ethiopia 's obn tv news...
731  ['ethiopian government and tigray rebels agree...
741  ['ethiopian government and tigray rebels agree...

                                           match_score  \
2    [0.5587443709373474, 0.5016520023345947, 0.449...
3    [0.6526452898979187, 0.6435942649841309, 0.678...
6    [0.601200520992279, 0.6149016618728638, 0.6060...
7    [0.5820202231407166, 0.5905984044075012, 0.544...
27   [0.5645926594734192, 0.5977888703346252, 0.582...
28   [0.5272127389907837, 0.5798885822296143, 0.626...
239  [0.5726739168167114, 0.48660898208618164, 0.74...
253  [0.6286035180091858, 0.589913010597229, 0.6039...
261  [0.6045465469360352, 0.5567666292190552, 0.560...
362  [0.5667229294776917, 0.5635765194892883, 0.525...
363  [0.43781614303588867, 0.4769328832626343, 0.55...
364  [0.5377827882766724, 0.729200541973114, 0.6012...
387  [0.6833693981170654, 0.5708960294723511, 0.712...
392  [0.5655810236930847, 0.39317408204078674, 0.50...
395  [0.42051348090171814, 0.4639887809753418, 0.54...
399  [0.46428030729293823, 0.44205382466316223, 0.7...
412  [0.4566322863101959, 0.3964540362358093, 0.454...
417  [0.5684945583343506, 0.5530351996421814, 0.598...
432  [0.5280206203460693, 0.5665380358695984, 0.395...
508  [0.7135055661201477, 0.44882047176361084, 0.49...
664  [0.5085923671722412, 0.4270167052745819, 0.476...
669  [0.5908374190330505, 0.5285086631774902, 0.557...
681  [0.4751462936401367, 0.549098014831543, 0.5594...
700  [0.39651721715927124, 0.446380615234375, 0.477...
708  [0.5308921337127686, 0.404721200466156, 0.5158...
715  [0.4109443128108978, 0.4499170184135437, 0.420...
716  [0.5230609774589539, 0.4988051652908325, 0.402...
720  [0.5539960861206055, 0.515402615070343, 0.4660...
723  [0.511408805847168, 0.4203908145427704, 0.7491...
731  [0.7604167461395264, 0.5627204775810242, 0.558...
741  [0.7485524415969849, 0.6427618265151978, 0.587...

                                      similarity_score  \
2    [0.6153846153846154, 0.5714285714285714, 0.615...
3    [0.3076923076923077, 0.3076923076923077, 0.32,...
6    [0.46153846153846156, 0.41379310344827586, 0.4...
7    [0.5769230769230769, 0.5172413793103449, 0.517...
27   [0.6153846153846154, 0.5517241379310345, 0.551...
28   [0.6538461538461539, 0.5862068965517241, 0.586...
239  [0.2962962962962963, 0.2692307692307692, 0.285...
253  [0.5384615384615384, 0.5, 0.5, 0.5185185185185...
261  [0.46153846153846156, 0.42857142857142855, 0.4...
362  [0.52, 0.5, 0.48148148148148145, 0.46428571428...
363  [0.2962962962962963, 0.28, 0.2962962962962963,...
364  [0.696969696969697, 0.7333333333333333, 0.7187...
387  [0.15384615384615385, 0.14814814814814814, 0.1...
392  [0.48, 0.42857142857142855, 0.4285714285714285...
395  [0.42857142857142855, 0.41379310344827586, 0.3...
399  [0.38461538461538464, 0.37037037037037035, 0.3...
412  [0.7333333333333333, 0.8518518518518519, 0.821...
417  [0.4444444444444444, 0.4444444444444444, 0.461...
432  [0.4583333333333333, 0.3793103448275862, 0.423...
508  [0.56, 0.5384615384615384, 0.5384615384615384,...
664  [0.3076923076923077, 0.3076923076923077, 0.307...
669  [0.4, 0.38461538461538464, 0.38461538461538464...
681  [0.34615384615384615, 0.34615384615384615, 0.3...
700  [0.5384615384615384, 0.5833333333333334, 0.464...
708  [0.38461538461538464, 0.35714285714285715, 0.3...
715  [0.3333333333333333, 0.3333333333333333, 0.333...
716  [0.46153846153846156, 0.5, 0.48, 0.44444444444...
720  [0.3333333333333333, 0.36, 0.32142857142857145...
723  [0.46153846153846156, 0.5, 0.42857142857142855...
731  [0.39285714285714285, 0.4583333333333333, 0.39...
741  [0.39285714285714285, 0.4074074074074074, 0.45...

                                        temporal_score  \
2    [0.7385, 0.495, 0.6817, 0.6355, 0.5809, 0.7385...
3    [0.8, 0.7385, 0.8, 0.7385, 0.7385, 0.7385, 0.4...
6    [0.9231, 0.6293, 0.6293, 0.6817, 0.9481, 0.681...
7    [0.8988, 0.6817, 0.6817, 0.6293, 0.457, 0.5363...
27   [0.5273, 0.6188, 0.6188, 0.5363, 0.6355, 0.726...
28   [0.5134, 0.6025, 0.6025, 0.5809, 0.6188, 0.707...
239  [0.8, 0.8988, 0.7385, 0.9737, 0.6817, 0.7385, ...
253  [0.495, 0.707, 0.7261, 0.6884, 0.6188, 0.8752,...
261  [0.9481, 0.5866, 0.5562, 0.707, 0.6884, 0.8297...
362  [0.5363, 0.6817, 0.6025, 0.8988, 0.8079, 0.786...
363  [0.9737, 0.9737, 0.7385, 0.8988, 0.9737, 0.738...
364  [0.5363, 0.6293, 0.5809, 0.8, 0.495, 0.5712, 0...
387  [0.7385, 0.8988, 0.7385, 0.6817, 0.7385, 0.8, ...
392  [0.5134, 0.8752, 0.6703, 0.6703, 0.6703, 0.898...
395  [0.8, 0.8, 0.8297, 0.8, 0.8521, 0.6884, 0.9481...
399  [0.8988, 0.8988, 0.5809, 0.7458, 0.8988, 0.948...
412  [0.5134, 0.6355, 0.6355, 0.8079, 0.7866, 0.707...
417  [0.5562, 0.707, 0.6884, 0.6188, 0.8079, 0.5562...
432  [0.8988, 0.7385, 0.9481, 0.7385, 0.9737, 0.8, ...
508  [0.7385, 0.8, 0.5363, 0.7866, 0.7385, 0.7385, ...
664  [0.9231, 0.9481, 0.9481, 0.9737, 0.9481, 0.973...
669  [0.7385, 0.9481, 0.6527, 0.8988, 0.9737, 0.898...
681  [0.9231, 0.8297, 0.7261, 0.6527, 0.7261, 0.726...
700  [0.8521, 0.7866, 0.7261, 0.9737, 0.6703, 0.618...
708  [0.8, 0.9737, 0.9231, 0.5866, 0.9737, 0.7866, ...
715  [0.9737, 0.9737, 0.9737, 0.6817, 0.8, 0.8079, ...
716  [0.8079, 0.8, 0.9737, 0.8, 0.8, 0.5363, 0.9737...
720  [0.7261, 0.8988, 0.8988, 0.8988, 0.8521, 0.875...
723  [0.6703, 0.8297, 0.7385, 0.8079, 0.8297, 0.829...
731  [0.7385, 0.6703, 0.8297, 0.6703, 0.7659, 0.738...
741  [0.7866, 0.9481, 0.5134, 0.6355, 0.5866, 0.786...

                                          final_scores match_Labels  \
2    [0.5606012341473877, 0.40757513981874055, 0.46...        Valid
3    [0.49456891479811427, 0.4648666081057521, 0.51...        Valid
6    [0.5842077067519167, 0.45597908454106106, 0.45...        Valid
7    [0.6189371774663814, 0.5112004370918815, 0.481...        Valid
27   [0.4826622483837513, 0.5084634251372591, 0.498...        Valid
28   [0.47180380636663805, 0.507415536132021, 0.537...        Valid
239  [0.43686848998878347, 0.40574951330174847, 0.5...        Valid
253  [0.47411238533495015, 0.512084420071643, 0.528...        Valid
261  [0.5960646773106142, 0.4088254249952207, 0.407...        Valid
362  [0.44071759152716694, 0.48513139355738194, 0.4...        Valid
363  [0.4162333651031419, 0.4337222342491308, 0.400...        Valid
364  [0.5087206336883001, 0.6872885517464359, 0.578...        Valid
387  [0.41527275158059107, 0.401239233231742, 0.437...        Valid
392  [0.4114769608130745, 0.4139420875563761, 0.408...        Valid
395  [0.4026478642076835, 0.423721692247895, 0.4667...        Valid
399  [0.4478334357658158, 0.4263596051180837, 0.507...        Valid
412  [0.46482919258023836, 0.5310510441446054, 0.55...        Valid
417  [0.41249076322409606, 0.460788311696842, 0.491...        Valid
432  [0.525546786989852, 0.44981025869642266, 0.441...        Valid
508  [0.6342555618785879, 0.4750277558925575, 0.401...        Valid
664  [0.4483566587328947, 0.4048810683715645, 0.437...        Valid
669  [0.47579786746925, 0.5087654488841258, 0.41341...        Valid
681  [0.4454416977544027, 0.4574740335463551, 0.424...        Valid
700  [0.46111488092619923, 0.49027506202365023, 0.4...        Valid
708  [0.45299311677013876, 0.42453412554764935, 0.4...        Valid
715  [0.4169028258683012, 0.4422963344264887, 0.423...        Valid
716  [0.488703526952323, 0.48871881213804347, 0.483...        Valid
720  [0.4142723220696308, 0.46906164752785956, 0.41...        Valid

In [407]:
def find_valid_event_ids(article_list_str):
        unique_lists = [valid_articles_map[a] for a in article_list_str if a in valid_articles_map]
        return list(set(unique_lists))

valid_events['valid_event_ids_from_matched'] = valid_events['article_id'].apply(find_valid_event_ids)

valid_events['has_valid_events'] = valid_events['valid_event_ids_from_matched'].apply(lambda x: len(x) > 0)

In [408]:
valid_events['article_id_count'] = valid_events['valid_article_ids_from_matched'].apply(lambda x: len(x) if isinstance(x, list) else 0)

In [409]:
valid_events['article_id_count']

2        8
3        8
6       31
7       62
27     301
28     305
239     31
253    110
261     84
362     98
363     12
364    199
387      9
392    132
395     94
399     48
412    160
417    111
432     39
508     35
664     24
669     93
681     47
700     37
708     26
715      9
716     48
720     39
723     99
731    152
741    150
Name: article_id_count, dtype: int64

In [410]:
valid_events['event_id_count'] = valid_events['valid_event_ids_from_matched'].apply(lambda x: len(x) if isinstance(x, list) else 0)

In [411]:
valid_events['event_id_count']

2       2
3       2
6       4
7       7
27     32
28     32
239    11
253    30
261    29
362    28
363     7
364    50
387     6
392    30
395    17
399    13
412    35
417    30
432    23
508     5
664     7
669    17
681    14
700    15
708    14
715     7
716    21
720    18
723    30
731    38
741    33
Name: event_id_count, dtype: int64

In [412]:
valid_events['article_id_count']

2        8
3        8
6       31
7       62
27     301
28     305
239     31
253    110
261     84
362     98
363     12
364    199
387      9
392    132
395     94
399     48
412    160
417    111
432     39
508     35
664     24
669     93
681     47
700     37
708     26
715      9
716     48
720     39
723     99
731    152
741    150
Name: article_id_count, dtype: int64

In [413]:
valid_events.to_csv("Third_dataset_acc.csv", index=False)

In [414]:
valid_events['valid_event_ids_from_matched'][2]

["['8c0f141014ed0e30e477501360774ceb48efb800ce58a06e4a26c3f72256aadd']",
 "['46d1d6d56a23cc7f56a8b44f86e4f93616a6cd1675a6df9cbef21ca5012ce696']"]

In [379]:
final_df = pd.read_csv('/Users/amalkurian/Desktop/Dissertation/Bias Detection/Deliverables/Data/Third_dataset.csv')

In [423]:
valid_events['article_id'][2]

[4,
 121,
 147,
 513,
 575,
 650,
 677,
 678,
 851,
 855,
 920,
 1019,
 1094,
 1102,
 1209,
 1272,
 1316,
 1377,
 1609,
 1658,
 1691,
 1698,
 1702,
 1754,
 1768,
 1834,
 1900,
 2001,
 2004,
 2081,
 2255,
 2272,
 2288,
 2310,
 2438,
 2539,
 2580,
 2622,
 2709,
 3020,
 3025,
 3057,
 3058,
 3063,
 3075,
 3076,
 3114,
 3115]

In [431]:
first_df_cropped['article_id'] = first_df_cropped['article_id'].apply(
    lambda x: ast.literal_eval(x) if isinstance(x, str) and x.startswith('[') else x
)

first_df_cropped['final_scores'] = first_df_cropped['final_scores'].apply(
    lambda x: ast.literal_eval(x) if isinstance(x, str) and x.startswith('[') else x
)

/var/folders/1_/1tlll79x3z32x6h88brvgx7r0000gn/T/ipykernel_36447/10435539.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  first_df_cropped['article_id'] = first_df_cropped['article_id'].apply(
/var/folders/1_/1tlll79x3z32x6h88brvgx7r0000gn/T/ipykernel_36447/10435539.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  first_df_cropped['final_scores'] = first_df_cropped['final_scores'].apply(

In [432]:
from collections import defaultdict
import pandas as pd

score_map = defaultdict(list)

for _, row in first_df_cropped.iterrows():
     if isinstance(row['article_id'], list) and isinstance(row['final_scores'], list):
        for aid, score in zip(row['article_id'], row['final_scores']):
            score_map[aid].append(score)

score_map = dict(score_map)

In [435]:
valid_events.to_csv('matched_events_part_II.csv', index=False)